using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpertosSeguridad.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddRequestNumberAndResolution : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Editado a mano. La versión generada agregaba directamente la columna de identidad, que numera
            // las filas existentes en orden físico (y declaraba un valor por defecto 0 junto a un índice
            // único). En su lugar, las solicitudes existentes se numeran por fecha de creación y la secuencia
            // de identidad arranca después del mayor número asignado.
            migrationBuilder.Sql("""
                ALTER TABLE maintenance_requests ADD COLUMN "Number" integer;

                UPDATE maintenance_requests AS request
                SET "Number" = numbered.position
                FROM (
                    SELECT "Id", row_number() OVER (ORDER BY "CreatedAt", "Id") AS position
                    FROM maintenance_requests
                ) AS numbered
                WHERE request."Id" = numbered."Id";

                ALTER TABLE maintenance_requests ALTER COLUMN "Number" SET NOT NULL;
                ALTER TABLE maintenance_requests ALTER COLUMN "Number" ADD GENERATED BY DEFAULT AS IDENTITY;

                SELECT setval(
                    pg_get_serial_sequence('maintenance_requests', 'Number'),
                    COALESCE((SELECT MAX("Number") FROM maintenance_requests), 0) + 1,
                    false);
                """);

            migrationBuilder.AddColumn<string>(
                name: "ResolutionDescription",
                table: "maintenance_requests",
                type: "character varying(2000)",
                maxLength: 2000,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ResolutionTitle",
                table: "maintenance_requests",
                type: "character varying(120)",
                maxLength: 120,
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "ResolvedAt",
                table: "maintenance_requests",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "ResolvedById",
                table: "maintenance_requests",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ResolvedByName",
                table: "maintenance_requests",
                type: "character varying(120)",
                maxLength: 120,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_maintenance_requests_number",
                table: "maintenance_requests",
                column: "Number",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_maintenance_requests_resolved_by_id",
                table: "maintenance_requests",
                column: "ResolvedById");

            migrationBuilder.AddForeignKey(
                name: "FK_maintenance_requests_users_ResolvedById",
                table: "maintenance_requests",
                column: "ResolvedById",
                principalTable: "users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_maintenance_requests_users_ResolvedById",
                table: "maintenance_requests");

            migrationBuilder.DropIndex(
                name: "ix_maintenance_requests_number",
                table: "maintenance_requests");

            migrationBuilder.DropIndex(
                name: "ix_maintenance_requests_resolved_by_id",
                table: "maintenance_requests");

            migrationBuilder.DropColumn(
                name: "Number",
                table: "maintenance_requests");

            migrationBuilder.DropColumn(
                name: "ResolutionDescription",
                table: "maintenance_requests");

            migrationBuilder.DropColumn(
                name: "ResolutionTitle",
                table: "maintenance_requests");

            migrationBuilder.DropColumn(
                name: "ResolvedAt",
                table: "maintenance_requests");

            migrationBuilder.DropColumn(
                name: "ResolvedById",
                table: "maintenance_requests");

            migrationBuilder.DropColumn(
                name: "ResolvedByName",
                table: "maintenance_requests");
        }
    }
}
